version: "3.0"

services:
    react:
        ports:
            - "3000:3000"
        volumes:
            - ./:/app
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "react-concert"



